# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kitemviews': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
