# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kdesignerplugin' : '@latest'
    'frameworks/kcontacts' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-contacts' : '@same'
    'kde/pim/akonadi-search' : '@same'
    'kde/pim/kldap' : '@same'
